# Generated by Django 5.2 on 2025-04-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
